version: '3'
services:
  swagger-ui:
    build: .
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/api-docs.yaml
    volumes:
      - ./api-docs.yaml:/usr/share/nginx/html/api-docs.yaml:ro