version: '3.8'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./api-docs.yaml:/usr/share/nginx/html/api-docs.yaml
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/api-docs.yaml
